// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLXQGZN-Usx5V46Ed35_qMywLmhCNbRE',
    appId: '1:306430599063:web:65b7176b1bf06d8ccf6ed2',
    messagingSenderId: '306430599063',
    projectId: 'qmart-6618b',
    authDomain: 'qmart-6618b.firebaseapp.com',
    databaseURL: 'https://qmart-6618b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qmart-6618b.appspot.com',
    measurementId: 'G-0R34FFXMRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn2g5q9YNuskNo7O3jif5ryuqTKRBZ6Bg',
    appId: '1:306430599063:android:b89001b6a6299939cf6ed2',
    messagingSenderId: '306430599063',
    projectId: 'qmart-6618b',
    databaseURL: 'https://qmart-6618b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qmart-6618b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqd4DHCltO1Pz1dSJHahRku9bPsEbaYj0',
    appId: '1:306430599063:ios:6b3b6375f30caee4cf6ed2',
    messagingSenderId: '306430599063',
    projectId: 'qmart-6618b',
    databaseURL: 'https://qmart-6618b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qmart-6618b.appspot.com',
    iosClientId: '306430599063-no64fivmd86iviaestchi5s0uh9hvs2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.qmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqd4DHCltO1Pz1dSJHahRku9bPsEbaYj0',
    appId: '1:306430599063:ios:6b3b6375f30caee4cf6ed2',
    messagingSenderId: '306430599063',
    projectId: 'qmart-6618b',
    databaseURL: 'https://qmart-6618b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qmart-6618b.appspot.com',
    iosClientId: '306430599063-no64fivmd86iviaestchi5s0uh9hvs2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.qmart',
  );
}
